### ISSUE TITLE
"close" event is not sent on Socket, if it is attached before the Socket upgrade

### ISSUE THREAD

**Issue by koush** [socketio/engine.io-server-java#10]
See here:
https://github.com/socketio/engine.io-server-java/blob/master/engine.io-server/src/main/java/io/socket/engineio/server/EngineIoSocket.java#L135

When the transport upgrades from XHR to WebSocket, all existing close events get cleared out. I am not sure if this is intended behavior, and I am currently working around it by reattaching close events upon receiving an upgrade event.

Repro
1. wait for "connection" event for EngineIOSocket.
2. Attach "close" event immediately on EngineIOSocket
3. Wait for EngineIOSocket client transport to upgrade. Should happen more or less immediately if websocket transport is configured.
4. Close browser or java engine io client
5. Observe that the "close" originally attached close event is not fired. It is not even in the internal callback list, because it was cleared during upgrade.

**Comment by trinopoty** [comment]
That is by design. The callbacks for the old transport is cleared and new ones are registered by calling`setTransport`.
I'll take a better look at it when I get the time.

**Comment by trinopoty** [comment]
It seems I read the original js sources a bit incorrectly.
This issue should now be fixed.
Can you please check it now.

**Comment by koush** [comment]
Yes, this seems to work fine. Great work on the library btw. I managed to port this to Android, on a custom http server stack, with zero changes. This was the only bug I encountered.
