### ISSUE TITLE
Clarification on XHR polling and handleRequest. Possible bug?

### ISSUE THREAD

**Issue by koush** [socketio/engine.io-server-java#11]
I've ported this fairly easily to a custom HTTP stack on Android. I did have a question around how a http server implementation of the engine.io-server-java is supposed to handle XHR polling and/or long running connections.

By default, it seems that engine.io-server-java gets an xhr request (handleRequest + HttpServletRequest), and immediately responds with NOOP. The client receives this completed request, and immediately sends another XHR poll request, which is then also immediately completed.
This results in the client hitting the server as fast as possible. Hundreds of requests per second. When/if the connection is upgraded to websockets, this hyper polling stops.

By default, it seems engine.io-server-java does not hold the XHR connection until the server needs to send data to the client. Is this intentional?

Currently, my workaround is to delay the handleRequest call with the Java equivalent of a setTimeout(handleReqest, 500). This limits the number of polls per second to 2.

**Comment by trinopoty** [comment]
Holding the connection open in Java was not a good idea when I tried. It starved the server thread pool. As such, this library returns immediately for an XHR request. I know this is not ideal but we're stuck with it for the time being.

If you know of a way to add a delay without starving the thread pool that works on all servers, please let me know.

**Comment by trinopoty** [comment]
I studied it a little bit and I must say, this particular bit is easier in Node.JS than Java.
I'll see what I can do about this in the future.

**Comment by koush** [comment]
I presumed as much. Jetty uses nonblocking IO, as does my http stack. There's basically no cost to holding requests. There's no thread pool where connections block. Similar to node.

However, the default Java SE uses blocking IO, one connection per thread. Holding connections on that server will certainly starve the server thread pool.

It's an implementation specific detail, I think. There's no way to hold a connection on a blocking socket. Any read will potentially block. The http server implementation could potentially not continue reading after the request headers, but the Java SE implementation probably doesn't do that. I think it probably just sits on a blocking read.

The long and short of it is that this is not possible unless you eliminate blocking io solutions from your list of supported servers.

Alternatively, only hold connections on nonblocking servers.

**Comment by koush** [comment]
As mentioned, I have worked around this by delaying the handling of the request myself. But this is less than ideal, since I do not have a way of knowing upon receiving the request, if there is data queued for the socket of that request. So my polling clients will never get pending data immediately, even if it is available.
500ms is not a deal breaker though.

**Comment by koush** [comment]
To be clear, as is, XHR polling is unusable on blocking and non blocking servers due to the immediate return. The server gets bombarded. If this is working as designed on the server, is there a way to have the client not immediately hit the server again? As far as I know, there isn't.

**Comment by trinopoty** [comment]
That bit is on the client side and cannot be changed without updating the client library.
However, this wasn't a problem in my use cases as the connection is upgraded to websocket almost immediately.
This will however be a big issue in XHR only environments.

**Comment by trinopoty** [comment]
This problem has been resolved in the latest release.
I'm closing this issue. Please re-open if you find any problems with the async polling.
