### ISSUE TITLE
Is EngineIoServer / EngineIoSocket thread-safe?

### ISSUE THREAD

**Issue by plaa** [socketio/engine.io-server-java#19]
The documentation (site / JavaDoc) does not state anywhere whether EngineIoServer or EngineIoSocket is thread-safe?  Can for example `socket.send` be called from any thread, or does it need to be synchronized by the user?

**Comment by trinopoty** [comment]
`socket.send` is indeed thread safe and does not need any synchronization on part of the user.
Anything that's not thread safe is an implementation issue.

**Comment by plaa** [comment]
It would be good to add this to the docs (preferably both on the general site and on each class in the Javadoc). If nothing is mentioned, the only safe thing is to assume classes are not thread-safe.

**Comment by trinopoty** [comment]
I'll update the document sometime soon.
You can also submit a PR for it if you want.
