### ISSUE TITLE
Can I use with socket.io-client-swift .?

### ISSUE THREAD

**Issue by abdussamad0** [socketio/engine.io-server-java#3]
I have to use socket.io-client-swift for client side with engine.io Java server, can i do this ?

**Comment by trinopoty** [comment]
This project only implements the engine.io server and not the socket.io server.
The socket.io Java server is currently in review but if you want to use it, you can find it [here](https://github.com/trinopoty/socket.io-server-java).
It should be possible to use the Java server with the Swift client.
