### ISSUE TITLE
A bug in engineio.parser.ParserV4

### ISSUE THREAD

**Issue by EasonLyo** [socketio/engine.io-server-java#38]
`public void encodePayload(List<Packet<?>> packets, boolean supportsBinary, EncodeCallback<Object> callback) {
        final String[] encodedPackets = new String[packets.size()];
        for (int i = 0; i < encodedPackets.length; i++) {
            final Packet<?> packet = packets.get(i);

            final int packetIdx = i;
            encodePacket(packet, false, data -> encodedPackets[packetIdx] = (String) data);
        }

        callback.call(String.join(SEPARATOR, encodedPackets));
    }`
it should be :
`public void encodePayload(List<Packet<?>> packets, boolean supportsBinary, EncodeCallback<Object> callback) {
        final String[] encodedPackets = new String[packets.size()];
        for (int i = 0; i < encodedPackets.length; i++) {
            final Packet<?> packet = packets.get(i);

            final int packetIdx = i;
            encodePacket(packet, supportsBinary, data -> encodedPackets[packetIdx] = (String) data);
        }

        callback.call(String.join(SEPARATOR, encodedPackets));
    }`
i fould the code during I runing the unit test in your project.

**Comment by trinopoty** [comment]
Version 3 and 4 of the socket.io protocol does not support binary encoding over polling transport.
Since `encodePayload` is only called by the polling transport, this piece of code is correct.

**Comment by EasonLyo** [comment]
thx for replay,i will close issue soon.

in fact,I have a idea to coding a socket.io serve by use vert.x and i have read socket.io-java-client ,engine-io-server,socketio-nodejs,can u give me some advice or idea?

In your perspective,Is vert.x suitable?

**Comment by trinopoty** [comment]
I don't have any experience with vert,x. You'll have to make any decisions on your own but I'd say go for it.
Sharing a single protocol across multiple tech stacks does have it's pros so it's never a bad thing to port socket.io to other stacks.

**Comment by EasonLyo** [comment]
thx and I'll give it a try!can u help me get some solution when i got any trouble about engine.io protocol or socket.io?

**Comment by trinopoty** [comment]
Sure. if you have any questions about the protocol, you can ask me and I'll try my best to answer.
