### ISSUE TITLE
Servlet 5 API support

### ISSUE THREAD

**Issue by mcollovati** [socketio/engine.io-server-java#51]
Are there any plans on supporting Jakarta Servlet 5 API, and more specifically the `javax` to `jakarta` namespace migration?

I did an experiment here [mcollovati/engine.io-server-java](https://github.com/mcollovati/engine.io-server-java/tree/jakarta-servlet) if it can be of any help

**Comment by trinopoty** [comment]
Hi,
Sorry for the delayed response.
Currently, we're considering if and how it would be possible to support both versions of the servlet api. Please keep watch for any update related to that.

**Comment by trinopoty** [comment]
Hi,
The latest version has been upgraded to jakarta api. Please give it a try if you're still waiting for it.
