### ISSUE TITLE
Spring Boot 2.6.* support

### ISSUE THREAD

**Issue by mattiapitossi** [socketio/engine.io-server-java#52]
Hi, 
I've been trying to follow https://socketio.github.io/engine.io-server-java/spring-integration.html for implementing engine.io in Spring Boot 2.6.*, but the guide seems to be outdated with more recent Spring Boot versions. 

Is it possibile to get an updated guide in order to use it?

Thanks

**Comment by trinopoty** [comment]
Hi,
The same guide should work for any 2.x version of spring boot.

**Comment by WirleySAlmeida** [comment]
Hi!

**Comment by WirleySAlmeida** [comment]
Hi!
I would like an example of usage with spring. I've used socket.io with node.js but not yet with java.
