### ISSUE TITLE
which protocol or engine.io-client js should be use?

### ISSUE THREAD

**Issue by aximo** [socketio/engine.io-server-java#6]
i use engine.io-java-server 1.1.1

if i use https://github.com/socketio/engine.io-client as javascript client , which release of that js should be used?

if i use 3.3.1 of engine.io-client, can i assign protocol number according https://github.com/socketio/engine.io-client#properties, if i can, which protocol number support in engine.io-java-server 1.1.1?

**Comment by trinopoty** [comment]
The latest release of the client js will work.
Note that the server library only supports version 3 of the protocol. This is the default so you don't need to add any extra configuration to the client js.

**Comment by aximo** [comment]
ok,thanks
