### ISSUE TITLE
Moving to Java 8+

### ISSUE THREAD

**Issue by trinopoty** [socketio/engine.io-server-java#7]
@darrachequesne I've tried to compile the library on Java 9+ and I've run into issues with uses of `DatatypeConverter` class. I originally used it because I set the min java version to 7. Dropping support for java 7 will allow me to use `Base64` class.
What are your views on dropping java 7 support?

**Comment by darrachequesne** [comment]
@trinopoty no problem on my side, Java7 has reached its EOL a few years ago ([ref](https://java.com/en/download/faq/java_7.xml)) so using it in production is not.. recommended, to say the least.

Especially if keeping it means an extra maintenance burden :ok_hand:

**Comment by Dmunch04** [comment]
I'm experiencing issues with the `AsyncListener` class. I'm on Java 11.0.5

**Comment by trinopoty** [comment]
Hi @Dmunch04 , can you please open a new issue detailing any errors you're getting?
