### ISSUE TITLE
i think it is convenient if put sid/EngineIoSocket as first param

### ISSUE THREAD

**Issue by aximo** [socketio/engine.io-server-java#9]

**Comment by trinopoty** [comment]
Can you please explain?

**Comment by aximo** [comment]
you are so quickly...

I notice the codes at io.socket.engineio.server.EngineIoSocket.onClose(String, String),i think it is convenient if put sid/EngineIoSocket as first param,right?

**Comment by trinopoty** [comment]
I was fixing the bug in SocketIoClient atm and I received the notification. So...quick.

**Comment by trinopoty** [comment]
That would violate the protocol defined in the js server library.
@darrachequesne comments?

**Comment by darrachequesne** [comment]
@aximo could you please explain what your use case is? Isn't `onClose` method private?

**Comment by trinopoty** [comment]
I think he's referring to putting the sid/object as the first parameter for the emitted events

**Comment by darrachequesne** [comment]
Something like the following:

```java
socket.on("message", (socket, args) -> {
  // ...
});
```
Doesn't it feel weird, from an `EventEmitter` point of vue?

**Comment by trinopoty** [comment]
I think he mentioned a central event handler in another issue. like `socket.on("message", handler)`, and the handler will be registered to multiple sockets.

That's why he wanted the socket as an arg.

**Comment by trinopoty** [comment]
I've added new methods on `EngineIoSocket` class that now provides the socket instance as the first argument.
It's available in version 5.0.0 which should be on maven in a few hours.
